# Sử dụng image nginx:latest làm base
FROM nginx:latest

# Sao chép file index.html vào thư mục mặc định của Nginx
COPY index.html /usr/share/nginx/html/

# Cổng mặc định của Nginx là 80, không cần khai báo EXPOSE vì image đã có sẵn