version: '3.8'
services:
  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://product-mongo:27017/product_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - product-mongo
      - kafka
  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://order-mongo:27017/order_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - order-mongo
      - kafka
      - product-service
      - customer-service
  customer-service:
    build: ./customer-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://customer-mongo:27017/customer_db
    depends_on:
      - customer-mongo
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - order-service
      - customer-service
  product-mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=product_db
    volumes:
      - product-data:/data/db
    ports:
      - "27017:27017" # Optional: để kiểm tra từ localhost
  order-mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=order_db
    volumes:
      - order-data:/data/db
    ports:
      - "27018:27017" 
  customer-mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=customer_db
    volumes:
      - customer-data:/data/db
    ports:
      - "27019:27017" 
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
volumes:
  product-data:
  order-data:
  customer-data: